# Generated by Django 3.2.7 on 2021-09-20 10:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import hrd_kantor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perusahaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('npp', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name_plural': 'DAFTAR PERUSAHAAN',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nik', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^\\d{16}$', 'Format NIK Tidak Sesuai')])),
                ('tgl_lahir', models.DateField()),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('propic', models.FileField(blank=True, null=True, upload_to=hrd_kantor.models.upload_name)),
                ('is_hrd', models.BooleanField(default=False)),
                ('npp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrd_kantor.perusahaan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
