# Generated by Django 3.2.7 on 2021-09-20 10:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hrd_kantor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoKPJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_kpj', models.CharField(max_length=11)),
                ('tgl_keps', models.DateField()),
                ('tgl_na', models.DateField(blank=True, null=True)),
                ('is_aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'DAFTAR KPJ',
                'verbose_name_plural': 'DAFTAR LIST KPJ',
            },
        ),
        migrations.CreateModel(
            name='TenagaKerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alamat', models.CharField(max_length=250)),
                ('nama_ibu', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('MENIKAH', 'MENIKAH'), ('TIDAK MENIKAH', 'TIDAK MENIKAH'), ('CERAI HIDUP', 'CERAI HIDUP'), ('CERAI MATI', 'CERAI MATI')], max_length=13)),
                ('nama_pasangan', models.CharField(blank=True, max_length=50, null=True)),
                ('tgl_lahir_psg', models.DateField(blank=True, null=True)),
                ('nama_anak_s', models.CharField(blank=True, max_length=50, null=True)),
                ('tgl_lahir_s', models.DateField(blank=True, null=True)),
                ('nama_anak_d', models.CharField(blank=True, max_length=50, null=True)),
                ('tgl_lahir_d', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('no_rekening', models.CharField(max_length=25)),
                ('nama_rekening', models.CharField(max_length=100)),
                ('file_kk', models.FileField(upload_to='tenaga-kerja/kk/', validators=[django.core.validators.RegexValidator('.*\\.(jpg|JPG|JPEG|pdf|PDF)', 'Only Support PDF dan JPG')])),
                ('file_ktp', models.FileField(upload_to='tenaga-kerja/ktp/', validators=[django.core.validators.RegexValidator('.*\\.(jpg|JPG|JPEG|pdf|PDF)', 'Only Support PDF dan JPG')])),
                ('file_paklaring', models.FileField(upload_to='tenaga-kerja/paklaring/', validators=[django.core.validators.RegexValidator('.*\\.(jpg|JPG|JPEG|pdf|PDF)', 'Only Support PDF dan JPG')])),
                ('file_lain', models.FileField(upload_to='tenaga-kerja/file-lain/', validators=[django.core.validators.RegexValidator('.*\\.(jpg|JPG|JPEG|pdf|PDF)', 'Only Support PDF dan JPG')])),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('kpj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.nokpj')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrd_kantor.profile')),
            ],
            options={
                'verbose_name': 'DATA TK',
                'verbose_name_plural': 'LIST DATA TK',
            },
        ),
    ]
